// packages/vue/src/button.tsx
import { Pressable as AriaPressable, type PressableProps as AriaPressableProps } from "@ark-ui/vue";
import { cva, type VariantProps } from "class-variance-authority";
import { defineComponent, type SlotsType, type VNodeChild } from "vue";

import { cn } from "@/lib/cn";

const styles = cva(
	"inline-flex shrink-0 items-center justify-center rounded-md text-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50",
	{
		variants: {
			variant: {
				primary: "bg-primary text-on-primary hover:bg-primary/90 data-[pressed]:bg-primary/90",
				secondary:
					"bg-secondary text-on-secondary hover:bg-secondary/80 data-[pressed]:bg-secondary/80",
				negative: "bg-negative text-on-negative hover:bg-negative/90 data-[pressed]:bg-negative/90",
				positive: "bg-positive text-on-positive hover:bg-positive/90 data-[pressed]:bg-positive/90",
				outline:
					"border border-input bg-background hover:bg-accent hover:text-on-accent data-[pressed]:bg-accent data-[pressed]:text-on-accent",
				ghost:
					"hover:bg-accent hover:text-on-accent data-[pressed]:bg-accent data-[pressed]:text-on-accent",
				link: "text-primary underline-offset-4 hover:underline data-[pressed]:underline",
			},
			size: {
				sm: "h-9 px-3",
				md: "h-10 px-4",
				lg: "h-11 px-8",
				icon: "s-10",
			},
		},
		defaultVariants: {
			variant: "primary",
			size: "md",
		},
	},
);

type ButtonStyleProps = VariantProps<typeof styles>;

export interface ButtonProps extends AriaPressableProps {
	/** @default 'md'' */
	size?: ButtonStyleProps["size"];
	/** @default 'primary'' */
	variant?: ButtonStyleProps["variant"];
}

export const Button = defineComponent({
	name: "Button",
	emits: ["press"],
	props: ["size", "variant"],
	slots: Object as SlotsType<{
		default?: () => VNodeChild;
	}>,
	setup(props: ButtonProps, { attrs, emit, slots }) {
		return () => {
			return (
				<AriaPressable
					{...attrs}
					class={cn(
						styles({
							class: attrs["class"] as string | undefined,
							size: props.size,
							variant: props.variant,
						}),
					)}
					onPress={(event) => {
						emit("press", event);
					}}
				>
					{slots.default?.()}
				</AriaPressable>
			);
		};
	},
});

// packages/ui-react/components/primitives/button.tsx
import { type GetVariantProps, styles } from "@acdh-oeaw/style-variants";
import type { ReactNode } from "react";
import {
	Button as AriaButton,
	type ButtonProps as AriaButtonProps,
	composeRenderProps,
} from "react-aria-components";

const buttonStyles = styles({
	base: [
		"relative isolate inline-flex items-baseline justify-center rounded-md text-center font-strong whitespace-nowrap transition select-none",
		"outline-stroke-focus focus:outline-hidden focus-visible:outline-2 focus-visible:outline-offset-2 forced-colors:outline-[Highlight]",
		"disabled:forced-colors:text-[GrayText]",
	],
	variants: {
		size: {
			xs: ["h-8 gap-x-2 px-3 py-1.5 text-xs/4.5", "*:data-[slot=icon]:size-3.5"],
			sm: ["h-9 gap-x-2 px-3.5 py-1.75 text-sm/5", "*:data-[slot=icon]:size-4"],
			md: ["h-10 gap-x-2 px-4 py-2.25 text-sm/5", "*:data-[slot=icon]:size-4"],
			lg: ["h-11 gap-x-2 px-4.5 py-2.25 text-base/6", "*:data-[slot=icon]:size-4.5"],
			xl: ["h-12 gap-x-2.5 px-5 py-2.75 text-base/6", "*:data-[slot=icon]:size-4.5"],
			"2xl": ["h-16 gap-x-3 px-7 py-4.75 text-base/6", "*:data-[slot=icon]:size-4.5"],
		},
		tone: {
			brand: [
				"[--_button-color-icon:var(--color-icon-brand)] [--_button-color-inverse:var(--color-text-inverse-strong)] [--_button-color-strong:var(--color-fill-brand-strong)] [--_button-color-weak:var(--color-fill-brand-weak)]",
			],
			neutral: [
				"[--_button-color-icon:var(--color-icon-neutral)] [--_button-color-inverse:var(--color-text-inverse-strong)] [--_button-color-strong:var(--color-fill-strong)] [--_button-color-weak:var(--color-fill-weak)]",
			],
			inverse: [
				"[--_button-color-icon:var(--color-icon-inverse)] [--_button-color-inverse:var(--color-text-strong)] [--_button-color-strong:var(--color-fill-inverse-strong)] [--_button-color-weak:var(--color-fill-inverse-weak)]",
			],
			negative: [
				"[--_button-color-icon:var(--color-icon-negative)] [--_button-color-inverse:var(--color-text-inverse-strong)] [--_button-color-strong:var(--color-fill-negative-strong)] [--_button-color-weak:var(--color-fill-negative-weak)]",
			],
			positive: [
				"[--_button-color-icon:var(--color-icon-positive)] [--_button-color-inverse:var(--color-text-inverse-strong)] [--_button-color-strong:var(--color-fill-positive-strong)] [--_button-color-weak:var(--color-fill-positive-weak)]",
			],
			warning: [
				"[--_button-color-icon:var(--color-icon-notice)] [--_button-color-inverse:var(--color-text-inverse-strong)] [--_button-color-strong:var(--color-fill-warning-strong)] [--_button-color-weak:var(--color-fill-warning-weak)]",
			],
			informative: [
				"[--_button-color-icon:var(--color-icon-informative)] [--_button-color-inverse:var(--color-text-inverse-strong)] [--_button-color-strong:var(--color-fill-informative-strong)] [--_button-color-weak:var(--color-fill-informative-weak)]",
			],
		},
		variant: {
			solid: [
				"border border-transparent bg-(--_button-color-strong) text-(--_button-color-inverse) shadow",
				"after:pointer-events-none after:absolute after:inset-0 after:rounded-[inherit] after:transition hover:after:bg-fill-hover",
				"disabled:bg-fill-disabled",
				"*:data-[slot=icon]:text-(--_button-color-icon)",
			],
			subtle: [
				"bg-(--_button-color-weak)",
				"after:pointer-events-none after:absolute after:inset-0 after:rounded-[inherit] after:transition hover:after:bg-fill-hover",
				"disabled:text-text-disabled",
				"*:data-[slot=icon]:text-(--_button-color-icon)",
			],
			outline: [
				"border border-(--_button-color-strong) text-(--_button-color-strong)",
				"after:pointer-events-none after:absolute after:inset-0 after:rounded-[inherit] after:transition hover:after:bg-fill-hover",
				"disabled:border-stroke-disabled disabled:text-text-disabled",
				"*:data-[slot=icon]:text-(--_button-color-icon)",
			],
			plain: [
				"*:data-[slot=icon]:text-(--_button-color-icon)",
				"after:pointer-events-none after:absolute after:inset-0 after:rounded-[inherit] after:transition hover:after:bg-fill-hover",
				"disabled:text-text-disabled",
			],
			text: [
				"text-(--_button-color-strong) underline",
				"disabled:text-text-disabled",
				"*:data-[slot=icon]:text-(--_button-color-icon)",
			],
		},
	},
	combinations: [],
	defaults: {
		size: "md",
		tone: "neutral",
		variant: "solid",
	},
});

type ButtonStylesProps = GetVariantProps<typeof buttonStyles>;

interface ButtonProps extends AriaButtonProps, ButtonStylesProps {}

export function Button(props: Readonly<ButtonProps>): ReactNode {
	const { children, className, size, tone, variant, ...rest } = props;

	return (
		<AriaButton
			{...rest}
			className={composeRenderProps(className, (className) => {
				return buttonStyles({ className, size, tone, variant });
			})}
		>
			{children}
		</AriaButton>
	);
}
