// packages/vue/src/button.tsx
import { Pressable as AriaPressable, type PressableProps as AriaPressableProps } from "@ark-ui/vue";
import { cva, type VariantProps } from "class-variance-authority";
import { defineComponent, type SlotsType, type VNodeChild } from "vue";

import { cn } from "@/lib/cn";

const styles = cva(
	"inline-flex shrink-0 items-center justify-center rounded-md text-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50",
	{
		variants: {
			variant: {
				primary: "bg-primary text-on-primary hover:bg-primary/90 data-[pressed]:bg-primary/90",
				secondary:
					"bg-secondary text-on-secondary hover:bg-secondary/80 data-[pressed]:bg-secondary/80",
				negative: "bg-negative text-on-negative hover:bg-negative/90 data-[pressed]:bg-negative/90",
				positive: "bg-positive text-on-positive hover:bg-positive/90 data-[pressed]:bg-positive/90",
				outline:
					"border border-input bg-background hover:bg-accent hover:text-on-accent data-[pressed]:bg-accent data-[pressed]:text-on-accent",
				ghost:
					"hover:bg-accent hover:text-on-accent data-[pressed]:bg-accent data-[pressed]:text-on-accent",
				link: "text-primary underline-offset-4 hover:underline data-[pressed]:underline",
			},
			size: {
				sm: "h-9 px-3",
				md: "h-10 px-4",
				lg: "h-11 px-8",
				icon: "s-10",
			},
		},
		defaultVariants: {
			variant: "primary",
			size: "md",
		},
	},
);

type ButtonStyleProps = VariantProps<typeof styles>;

export interface ButtonProps extends AriaPressableProps {
	/** @default 'md'' */
	size?: ButtonStyleProps["size"];
	/** @default 'primary'' */
	variant?: ButtonStyleProps["variant"];
}

export const Button = defineComponent({
	name: "Button",
	emits: ["press"],
	props: ["size", "variant"],
	slots: Object as SlotsType<{
		default?: () => VNodeChild;
	}>,
	setup(props: ButtonProps, { attrs, emit, slots }) {
		return () => {
			return (
				<AriaPressable
					{...attrs}
					class={cn(
						styles({
							class: attrs["class"] as string | undefined,
							size: props.size,
							variant: props.variant,
						}),
					)}
					onPress={(event) => {
						emit("press", event);
					}}
				>
					{slots.default?.()}
				</AriaPressable>
			);
		};
	},
});

// packages/react/src/components/button.tsx
"use client";

import type { ElementRef } from "react";
import {
	Button as AriaButton,
	type ButtonProps as AriaButtonProps,
	composeRenderProps,
} from "react-aria-components";

import { type ForwardedRef, forwardRef } from "@/lib/forward-ref";
import { compose, type VariantProps, variants } from "@/lib/styles";
import { focusRing } from "@/styles/focus-ring";

export const buttonStyles = compose(
	focusRing,
	variants({
		base: "inline-flex cursor-default items-center justify-center gap-2 whitespace-nowrap rounded-md px-5 py-2 text-center text-sm font-medium transition",
		variants: {
			size: {
				sm: "h-8 px-3 text-xs",
				md: "h-9 px-4 py-2",
				lg: "h-10 px-8",
			},
			variant: {
				primary:
					"bg-primary text-primary-foreground shadow-sm hover:bg-primary/90 pressed:bg-primary/80",
				secondary:
					"bg-secondary text-secondary-foreground shadow-sm hover:bg-secondary/80 pressed:bg-secondary/70",
				negative:
					"bg-negative text-negative-foreground shadow-sm hover:bg-negative/90 pressed:bg-negative/80",
				outline:
					"border border-input bg-background shadow-sm hover:bg-accent hover:text-accent-foreground pressed:bg-accent/90",
				ghost: "hover:bg-accent hover:text-accent-foreground pressed:bg-accent/90",
				link: "text-primary underline-offset-4 hover:underline",
			},
			isDisabled: {
				true: "disabled:opacity-50 forced-colors:text-[GrayText]",
			},
		},
		defaultVariants: {
			size: "md",
			variant: "primary",
		},
	}),
);

export type ButtonStyles = VariantProps<typeof buttonStyles>;

export interface ButtonProps extends AriaButtonProps, ButtonStyles {}

export const Button = forwardRef(function Button(
	props: ButtonProps,
	forwardedRef: ForwardedRef<ElementRef<typeof AriaButton>>,
) {
	const { children, className, variant, ...rest } = props;

	return (
		<AriaButton
			ref={forwardedRef}
			{...rest}
			className={composeRenderProps(className, (className, renderProps) => {
				return buttonStyles({ ...renderProps, className, variant });
			})}
		>
			{children}
		</AriaButton>
	);
});
